### ISSUE TITLE
Problem with 1.1.0 release (with webpack)

### ISSUE THREAD

**Issue by benediktvaldez** [bevry/sortobject#3]
There seems to be a problem with the latest release, using webpack

Works fine when using version 1.0.0

First error is
```
WARNING in ../~/sortobject/index.js
Critical dependencies:
3:63-70 require function is used in a way in which dependencies cannot be statically extracted
 @ ../~/sortobject/index.js 3:63-70
```

Next we get loads of something like this
```
WARNING in ../~/sortobject/package.json
Module parse failed: /path/to/project/node_modules/sortobject/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
    at Parser.pp.raise (/path/to/project/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.unexpected (/path/to/project/node_modules/acorn/dist/acorn.js:1483:8)
    at Parser.pp.semicolon (/path/to/project/node_modules/acorn/dist/acorn.js:1462:73)
    at Parser.pp.parseExpressionStatement (/path/to/project/node_modules/acorn/dist/acorn.js:1976:8)
    at Parser.pp.parseStatement (/path/to/project/node_modules/acorn/dist/acorn.js:1754:188)
    at Parser.pp.parseBlock (/path/to/project/node_modules/acorn/dist/acorn.js:1991:21)
    at Parser.pp.parseStatement (/path/to/project/node_modules/acorn/dist/acorn.js:1735:19)
    at Parser.pp.parseTopLevel (/path/to/project/node_modules/acorn/dist/acorn.js:1648:21)
    at Parser.parse (/path/to/project/node_modules/acorn/dist/acorn.js:1616:17)
    at Object.parse (/path/to/project/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/path/to/project/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/path/to/project/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.provide (/path/to/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:52:20)
    at CachedInputFileSystem.readFile (/path/to/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:140:24)
    at DependenciesBlock.onLoadPitchDone (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:255:7)
    at DependenciesBlock.loadPitch (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:182:27)
    at DependenciesBlock.doBuild (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:241:4)
    at DependenciesBlock.build (/path/to/project/node_modules/webpack/lib/NormalModule.js:84:14)
    at Compilation.buildModule (/path/to/project/node_modules/webpack/lib/Compilation.js:126:9)
 @ ../~/sortobject ^\.\/.*$

 WARNING in ../~/sortobject/HISTORY.md
Module parse failed: /path/to/project/node_modules/sortobject/HISTORY.md Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
    at Parser.pp.raise (/path/to/project/node_modules/acorn/dist/acorn.js:920:13)
    at Parser.pp.getTokenFromCode (/path/to/project/node_modules/acorn/dist/acorn.js:2813:8)
    at Parser.pp.readToken (/path/to/project/node_modules/acorn/dist/acorn.js:2508:15)
    at Parser.pp.nextToken (/path/to/project/node_modules/acorn/dist/acorn.js:2500:71)
    at Parser.parse (/path/to/project/node_modules/acorn/dist/acorn.js:1615:10)
    at Object.parse (/path/to/project/node_modules/acorn/dist/acorn.js:882:44)
    at Parser.parse (/path/to/project/node_modules/webpack/lib/Parser.js:902:15)
    at DependenciesBlock.<anonymous> (/path/to/project/node_modules/webpack/lib/NormalModule.js:104:16)
    at DependenciesBlock.onModuleBuild (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /path/to/project/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/path/to/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /path/to/project/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:404:3)
 @ ../~/sortobject ^\.\/.*$
```

**Comment by tommcgurl** [comment]
👍

**Comment by balupton** [comment]
Does webpack not support the `browser` field? Browserify uses this.

**Comment by balupton** [comment]
Ok. Browser field has been specified incorrectly. I will do an update soon.

**Comment by balupton** [comment]
v1.1.1 published give that a go

**Comment by balupton** [comment]
Heading off. Will be back in a few hours. Let me know how the above gos, and if there is anything more for me to do.

**Comment by benediktvaldez** [comment]
Thanks @balupton for a swift response! This seems to work perfectly now, at least for us :+1:

![BRAVO](https://i.imgur.com/o59OOxo.gif)

**Comment by tommcgurl** [comment]
Thanks @balupton for the quick fix! Thanks to @benediktvaldez for opening the issue. 👍 😄
